FROM registry.cn-hangzhou.aliyuncs.com/theia-docker/theia-java:1.0.0

# 添加Tomcat插件
ADD vscode-tomcat-0.12.1.tar.gz ./plugins/vscode-tomcat-0.12.1.tar.gz
# RUN tar -zxvf ./plugins/vscode-tomcat-0.12.1.tar.gz \
#     && rm -rf ./plugins/vscode-tomcat-0.12.1.tar.gz